"""Daily email report generation and sending."""

import smtplib
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from homesearch.config import settings
from homesearch.models import Listing, SavedSearch
from homesearch import database as db
from homesearch.services.search_service import run_search


def generate_report() -> dict:
    """Run all active saved searches and return report data.

    Returns dict of {search_name: {"search": SavedSearch, "new_listings": list[Listing], "total": int}}
    """
    db.init_db()
    searches = db.get_saved_searches(active_only=True)
    report_data = {}

    for search in searches:
        # Mark existing results as not new before running
        if search.id is not None:
            db.mark_results_not_new(search.id)

        # Run the search (will persist and mark new ones)
        all_results = run_search(search.criteria, search_id=search.id)

        # Get only the new listings
        new_listings = db.get_search_results(search.id, new_only=True) if search.id else []

        report_data[search.name] = {
            "search": search,
            "new_listings": new_listings,
            "total": len(all_results),
        }

    return report_data


def build_html_report(report_data: dict) -> str:
    """Build an HTML email body from report data."""
    now = datetime.now().strftime("%B %d, %Y")

    html = f"""<!DOCTYPE html>
<html>
<head><style>
    body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; margin: 0; padding: 20px; background: #f5f5f5; }}
    .container {{ max-width: 700px; margin: 0 auto; background: white; border-radius: 8px; padding: 24px; }}
    h1 {{ color: #1a1a2e; border-bottom: 2px solid #0066cc; padding-bottom: 10px; }}
    h2 {{ color: #333; margin-top: 24px; }}
    .search-section {{ margin-bottom: 30px; }}
    .stats {{ color: #666; font-size: 14px; margin-bottom: 12px; }}
    .property {{ display: flex; gap: 16px; padding: 12px; border: 1px solid #e0e0e0; border-radius: 8px; margin-bottom: 10px; }}
    .property img {{ width: 150px; height: 110px; object-fit: cover; border-radius: 6px; background: #eee; }}
    .property-info {{ flex: 1; }}
    .property-info h3 {{ margin: 0 0 6px 0; font-size: 16px; }}
    .property-info h3 a {{ color: #0066cc; text-decoration: none; }}
    .property-info h3 a:hover {{ text-decoration: underline; }}
    .price {{ color: #16a34a; font-weight: bold; font-size: 18px; }}
    .details {{ color: #666; font-size: 13px; margin-top: 4px; }}
    .no-new {{ color: #999; font-style: italic; }}
    .badge {{ display: inline-block; background: #0066cc; color: white; padding: 2px 8px; border-radius: 12px; font-size: 11px; margin-left: 6px; }}
</style></head>
<body>
<div class="container">
    <h1>🏠 HomeSearch Daily Report</h1>
    <p style="color: #666;">{now}</p>
"""

    total_new = 0
    for name, data in report_data.items():
        new_listings = data["new_listings"]
        total = data["total"]
        total_new += len(new_listings)

        html += f'<div class="search-section">'
        html += f'<h2>{name} <span class="badge">{len(new_listings)} new</span></h2>'
        html += f'<p class="stats">{total} total matches | {len(new_listings)} new since last check</p>'

        if not new_listings:
            html += '<p class="no-new">No new listings since last check.</p>'
        else:
            for listing in new_listings[:20]:  # Cap at 20 per search in email
                html += _listing_html(listing)

        html += '</div>'

    if total_new == 0:
        html += '<p style="text-align: center; color: #999; padding: 20px;">No new listings today across all your searches. We\'ll keep looking!</p>'

    html += """
    <hr style="border: none; border-top: 1px solid #e0e0e0; margin-top: 30px;">
    <p style="color: #999; font-size: 12px; text-align: center;">
        Generated by HomeSearch Aggregator | Run <code>homesearch serve</code> to view all results
    </p>
</div></body></html>"""

    return html


def _listing_html(listing: Listing) -> str:
    price_str = f"${listing.price:,.0f}" if listing.price else "Price N/A"
    details = []
    if listing.bedrooms:
        details.append(f"{listing.bedrooms} bed")
    if listing.bathrooms:
        details.append(f"{listing.bathrooms:.0f} bath")
    if listing.sqft:
        details.append(f"{listing.sqft:,} sqft")
    if listing.year_built:
        details.append(f"Built {listing.year_built}")
    if listing.has_garage:
        details.append("Garage")
    if listing.has_basement:
        details.append("Basement")

    detail_str = " · ".join(details) if details else ""
    img_html = f'<img src="{listing.photo_url}" alt="Property">' if listing.photo_url else '<div style="width:150px;height:110px;background:#ddd;border-radius:6px;display:flex;align-items:center;justify-content:center;color:#999;">No Photo</div>'
    link = listing.source_url or "#"

    return f"""<div class="property">
    {img_html}
    <div class="property-info">
        <h3><a href="{link}" target="_blank">{listing.address}</a></h3>
        <div class="price">{price_str}</div>
        <div class="details">{detail_str}</div>
        <div class="details" style="margin-top:4px;">Source: {listing.source} | {listing.zip_code}</div>
    </div>
</div>"""


def send_email_report(report_data: dict) -> bool:
    """Send the HTML report via SMTP. Returns True on success."""
    if not settings.smtp_user or not settings.smtp_password or not settings.report_email:
        print("[Report] SMTP not configured. Set SMTP_USER, SMTP_PASSWORD, REPORT_EMAIL in .env")
        return False

    html = build_html_report(report_data)

    total_new = sum(len(d["new_listings"]) for d in report_data.values())
    subject = f"HomeSearch: {total_new} new listing{'s' if total_new != 1 else ''} found"

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = settings.smtp_user
    msg["To"] = settings.report_email
    msg.attach(MIMEText(html, "html"))

    try:
        with smtplib.SMTP(settings.smtp_host, settings.smtp_port) as server:
            server.starttls()
            server.login(settings.smtp_user, settings.smtp_password)
            server.sendmail(settings.smtp_user, settings.report_email, msg.as_string())
        print(f"[Report] Email sent to {settings.report_email}")
        return True
    except Exception as e:
        print(f"[Report] Failed to send email: {e}")
        return False
